### ISSUE TITLE
Ui issue for desktop mode of calculator app!

### ISSUE THREAD

**Issue by Rajat069** [TeoBale/Calculator-PWA#1]
![image](https://github.com/TeoBale/Calculator-PWA/assets/72992710/58af6c44-c5ee-4c8c-9bb4-b60b282d98b8)

**Comment by TeoBale** [comment]
yes i am aware of the problem.. actually it is not the only one in this repo.. it is a little project of one afternoon just to experiment with using [Vite pwa plugin](https://vite-pwa-org.netlify.app/).

When I have time I will entirely rewrite the code of this app and also fix the responsivity issues
